import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";
import ContactNav from "@/components/contactNav";
import HydrationFix from "./hydration-fix";
import { ThemeProvider } from "@/contexts/ThemeContext";
import DynamicBackground from "@/components/DynamicBackground";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Jaytrons | Home",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        suppressHydrationWarning
      >
       <HydrationFix />
       <ThemeProvider>
         <DynamicBackground />
         <div className="flex flex-col min-h-screen  mx-auto ">
          <ContactNav />
         <Navbar />
         <div className="">
         {children}
         </div>
         </div>
       </ThemeProvider>
      </body>
    </html>
  );
}
